services:
  ### Postgres database for Products
  db-orders:
    container_name: db-new-orders
    image: postgres:16-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_orders
      POSTGRES_USER: cessadev
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### Postgres database for Keycloak
  db-keycloak:
    container_name: db-new-keycloak
    image: postgres:16-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: cessadev
      POSTGRES_PASSWORD: root
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  ### Keycloak
  keycloak:
    container_name: new-keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    command: [ "start-dev" ]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-new-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: cessadev
      DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181
      KC_HOSTNAME: localhost
      KC_HTTP_RELATIVE_PATH: /auth
